# Generated by Django 4.2.5 on 2024-10-01 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_description', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
