# Generated by Django 4.2.5 on 2024-10-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desctiption',
            new_name='product_description',
        ),
    ]
